package pro1.pro2.datamodel;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIgnore;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName="announcement")
public class Announcement {
	private String announcementId;
	private String announcementText;
	private String courseId;
	private String id;
	public Announcement() {
		
	}
	
	public Announcement(String announcementId, String announcementText, String courseId) {
		this.announcementId = announcementId;
		this.announcementText = announcementText;
		this.courseId = courseId;
	}
	
	
	@DynamoDBAttribute(attributeName="announcementText")
	public String getAnnouncementText() {
		return announcementText;
	}
	public void setAnnouncementText(String announcementText) {
		this.announcementText = announcementText;
	}
	@DynamoDBHashKey(attributeName="id")
	@DynamoDBAutoGeneratedKey
	public String getId() {
		return id;
	}
	public void setId(String id) {
		this.id = id;
	}
	@DynamoDBIndexHashKey(globalSecondaryIndexName="courseid-announcementid-index",attributeName="courseid")
	public String getCourseId() {
		return courseId;
	}
	public void setCourseId(String courseId) {
		this.courseId = courseId;
	}
	@DynamoDBIndexRangeKey(attributeName="announcementid",
			globalSecondaryIndexName = "courseid-announcementid-index")
	public String getAnnouncementId() {
		return announcementId;
	}
	public void setAnnouncementId(String announcementId) {
		this.announcementId = announcementId;
	}
	
	
	@DynamoDBIgnore
	@Override
	public String toString() { 
		return "AnnouncementId="+getAnnouncementId()+"BoardId=" + getCourseId() + ", announcementText=" + getAnnouncementText();
	}
}

