package pro1.pro2.datamodel;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIgnore;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName="Registrar")
public class Registrar
 {
	private String id;
	private String registrarId;
	private String offeringId;
	private String offeringType;
	private String department;
	private Integer perUnitPrice;
	public Registrar() {
		
	}
	
	public Registrar(String RegistrarId,String OfferingId, String OfferingType,String Department,int PerUnitPrice) {
		this.registrarId = registrarId;
		this.offeringId = offeringId;
		this.offeringType = offeringType;
		this.department = department;
		this.perUnitPrice = perUnitPrice;
	}
	
	@DynamoDBAttribute(attributeName="OfferingId")
	public String getOfferingId() {
		return offeringId;
	}
	public void setOfferingId(String OfferingId) {
		this.offeringId = OfferingId;
	}
	@DynamoDBIndexHashKey(globalSecondaryIndexName="RegistrarId",attributeName="RegistrarId")
	public String getRegistrarId() {
		return registrarId;
	}
	public void setRegistrarId(String RegistrarId) {
		this.registrarId = RegistrarId;
	}
	
	@DynamoDBHashKey(attributeName="id")
	@DynamoDBAutoGeneratedKey
	public String getId() {
		return id;
	}
	public void setId(String id) {
		this.id = id;
	}
	
	@DynamoDBAttribute(attributeName="OfferingType")
	public String getOfferingType() {
		return offeringType;
	}
	public void setOfferingType(String OfferingType) {
		this.offeringType = OfferingType;
	}
	
	@DynamoDBAttribute(attributeName="Department")
	public String getDepartment() {
		return department;
	}
	public void setDepartment(String Department) {
		this.department = Department;
	}
	
	@DynamoDBAttribute(attributeName="PerUnitPrice")
	public Integer getPerUnitPrice() {
		return perUnitPrice;
	}
	public void setPerUnitPrice(Integer PerUnitPrice) {
		this.perUnitPrice = PerUnitPrice;
	}
	
}
