package pro1.pro2.datamodel;

import java.util.ArrayList;
import java.util.List;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIgnore;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName="student")
public class Student {
	private String id;
	private String studentId;
	private String firstName;
	private String lastName;
	private String joiningDate;
	private String department;
	private String emailId;
	private List<String> registeredCourses;
	
	public Student() {
		
	}
	
	public Student(String studentId, String firstName, String lastName, String joiningDate, String department,String emailId) {
		this.studentId = studentId;
		this.firstName = firstName;
		this.lastName = lastName;
		this.joiningDate = joiningDate;
		this.department = department;
		this.emailId = emailId;
		this.registeredCourses = new ArrayList<>();
	}
	
	@DynamoDBIndexHashKey(globalSecondaryIndexName="studentid",attributeName="studentid")
	public String getStudentId() {
		return studentId;
	}
	public void setStudentId(String studentId) {
		this.studentId = studentId;
	}
	@DynamoDBHashKey(attributeName="id")
	@DynamoDBAutoGeneratedKey
	public String getId() {
		return id;
	}
	public void setId(String id) {
		this.id = id;
	}
	@DynamoDBAttribute(attributeName="firstName")
	public String getFirstName() {
		return firstName;
	}
	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}
	@DynamoDBAttribute(attributeName="lastName")
	public String getLastName() {
		return lastName;
	}
	public void setLastName(String lastName) {
		this.lastName = lastName;
	}
	@DynamoDBAttribute(attributeName="joiningDate")
	public String getJoiningDate() {
		return joiningDate;
	}
	public void setJoiningDate(String joiningDate) {
		this.joiningDate = joiningDate;
	}
	@DynamoDBAttribute(attributeName="department")
	public String getDepartment() {
		return department;
	}
	public void setDepartment(String department) {
		this.department = department;
	}
	
	@DynamoDBAttribute(attributeName="emailId")
	public String getEmailId() {
		return emailId;
	}
	public void setEmailId(String emailId) {
		this.emailId = emailId;
	}
	
	@DynamoDBAttribute(attributeName="registeredCourses")
	public List<String> getRegisteredCourses() {
		return registeredCourses;
	}
	public void setRegisteredCourses(List<String> courseIds) {
		this.registeredCourses = courseIds;
	}
	@DynamoDBIgnore
	@Override
	public String toString() { 
		return "StudentId=" + getStudentId() + ", firstName=" + getFirstName();
	}
}




//@XmlRootElement
//public class Student {
//	private String name;
//	private long studentId;
//	private long photo;
//	private List<Course> enrolled;
//	private Program program;
//	
//	public Student() {
//		
//	}
//    
//	public Student(long studentId, String name, long photo, Program program) {
//		this.studentId = studentId;
//		this.name = name;
//		this.photo = photo;
//		this.program = program;
//	}
//	public String getName() {
//		return name;
//	}
//
//	public void setName(String name) {
//		this.name = name;
//	}
//
//	public long getStudentId() {
//		return studentId;
//	}
//
//	public void setStudentId(long studentId) {
//		this.studentId = studentId;
//	}
//
//	public long getPhoto() {
//		return photo;
//	}
//
//	public void setPhoto(long photo) {
//		this.photo = photo;
//	}
//
//	public List<Course> getEnrolled() {
//		return enrolled;
//	}
//
//	public void setEnrolled(List<Course> enrolled) {
//		this.enrolled = enrolled;
//	}
//
//	public Program getProgram() {
//		return program;
//	}
//
//	public void setProgram(Program program) {
//		this.program = program;
//	}
//	
//}
